### ISSUE TITLE
db2_fdw;

### ISSUE THREAD

**Issue by hunterqq18ok** [wolfgangbrandl/db2_fdw#17]
Hi,good 
   I got a issue after I reboot my redhat as below 
postgres=# create extension db2_fdw;
ERROR:  could not load library "/usr/pgsql-10/lib/db2_fdw.so": libdb2ci.so.1: cannot open shared object file: No such file or directory
Could you give me a guide to how analysis this issue? Thanks!

**Comment by hunterqq18ok** [comment]
I run lld ldd /usr/pgsql-10/lib/db2_fdw.so find libdb2ci.so.1's file was contained in /home/db2inst1/sqllib/lib64/libdb2ci.so.1,
ldd /usr/pgsql-10/lib/db2_fdw.so
	linux-vdso.so.1 =>  (0x00007fffbcfea000)
	libdb2ci.so.1 => /home/db2inst1/sqllib/lib64/libdb2ci.so.1 (0x00007f3cf2c01000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f3cf2834000)
	libcrypt.so.1 => /usr/lib64/libcrypt.so.1 (0x00007f3cf25fd000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f3cf23f9000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f3cf21dd000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f3cf1edb000)
	libdb2.so.1 => /home/db2inst1/sqllib/lib64/libdb2.so.1 (0x00007f3ceeb08000)
	libdb2g11n.so.1 => /home/db2inst1/sqllib/lib64/libdb2g11n.so.1 (0x00007f3cee123000)
	libdb2osse.so.1 => /home/db2inst1/sqllib/lib64/libdb2osse.so.1 (0x00007f3ced95c000)
	libdb2osse_db2.so.1 => /home/db2inst1/sqllib/lib64/libdb2osse_db2.so.1 (0x00007f3ced6c5000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f3ced3be000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f3ced1a8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3cf3118000)
	libfreebl3.so => /usr/lib64/libfreebl3.so (0x00007f3cecfa5000)
	libpam.so.0 => /usr/lib64/libpam.so.0 (0x00007f3cecd96000)
	libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f3ceca2c000)
	libdb2dascmn.so.1 => /home/db2inst1/sqllib/lib64/libdb2dascmn.so.1 (0x00007f3cec7ff000)
	libdb2genreg.so.1 => /home/db2inst1/sqllib/lib64/libdb2genreg.so.1 (0x00007f3cec5b7000)
	libdb2install.so.1 => /home/db2inst1/sqllib/lib64/libdb2install.so.1 (0x00007f3cec3a3000)
	libdb2locale.so.1 => /home/db2inst1/sqllib/lib64/libdb2locale.so.1 (0x00007f3cec17c000)
	libdb2sdbin.so.1 => /home/db2inst1/sqllib/lib64/libdb2sdbin.so.1 (0x00007f3cebee0000)
	libdb2trcapi.so.1 => /home/db2inst1/sqllib/lib64/libdb2trcapi.so.1 (0x00007f3cebcc3000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00007f3cebabb000)
	libaudit.so.1 => /usr/lib64/libaudit.so.1 (0x00007f3ceb892000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00007f3ceb67c000)
	liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f3ceb456000)
	libcap-ng.so.0 => /usr/lib64/libcap-ng.so.0 (0x00007f3ceb250000)
and then I copied it into pgsql lib,and then the problem gone

**Comment by manovah2604** [comment]
@hunterqq18ok  what files need to be copied in pgsql lib ?

**Comment by wolfgangbrandl** [comment]
Hi
If you start postgres directly with pg_ctl on the CLI you have to include the db2 lib path into the LD_LIBRARY_PATH. 
If you start with systemctl than you have to set LD_LIBRARY_PATHin the service file.
