### ISSUE TITLE
Having issue while running make. Error: db2ci.h: No such file or directory

### ISSUE THREAD

**Issue by rajkamal321** [wolfgangbrandl/db2_fdw#34]
db2_fdw-master]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -g -fPIC -I/home/db2inst1/sqllib/include -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o db2_utils.o db2_utils.c
db2_utils.c:23:19: fatal error: db2ci.h: No such file or directory
 #include <db2ci.h>
                   ^
compilation terminated.
make: *** [db2_utils.o] Error 1

=============================
We have .bash_profile as below.

 root]# cat .bash_profile
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/usr/pgsql-10/bin

DB2INSTANCE=db2inst1
IBM_DB_LIB=/home/db2inst1/sqllib/lib
IBM_DB_DIR=/home/db2inst1/sqllib
USER=db2inst1
LD_LIBRARY_PATH=/home/db2inst1/sqllib/lib64:/home/db2inst1/sqllib/lib64/gskit:/home/db2inst1/sqllib/lib32
IBM_DB_HOME=/home/db2inst1/sqllib
MAIL=/var/spool/mail/db2inst1
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/db2inst1/sqllib/bin:/home/db2inst1/sqllib/adm:/home/db2inst1/sqllib/misc:/home/db2inst1/sqllib/gskit/bin:/home/db2inst1/.local/bin:/home/db2inst1/bin:/home/db2inst1/bin:/usr/pgsql-10/bin
DB2_HOME=/home/db2inst1/sqllib
HOME=/home/db2inst1
IBM_DB_INCLUDE=/home/db2inst1/sqllib/include
LOGNAME=db2inst1
CLASSPATH=/home/db2inst1/sqllib/java/db2java.zip:/home/db2inst1/sqllib/function:/home/db2inst1/sqllib/java/db2jcc_license_cu.jar:/home/db2inst1/sqllib/tools/clpplus.jar:/home/db2inst1/sqllib/tools/jline-0.9.93.jar:/home/db2inst1/sqllib/java/db2jcc.jar:.
DB2LIB=/home/db2inst1/sqllib/lib

export PATH DB2INSTANCE IBM_DB_LIB IBM_DB_DIR USER LD_LIBRARY_PATH IBM_DB_HOME MAIL DB2_HOME HOME IBM_DB_INCLUDE LOGNAME CLASSPATH DB2LIB

Please assist us to fix the issue.

**Comment by rajkamal321** [comment]
We have manual copied the missing db2ci.h file from other location and fixed the issue. We are able to create the db2_fdw now.

**Comment by wolfgangbrandl** [comment]
Hi

Db2ci,h i spart of the DB2 Installation.

Only db2 LUW is supported.

 

From: Ravazzini Andrea ***@***.***>
Reply to: wolfgangbrandl/db2_fdw ***@***.***>
Date: Wednesday, 5. October 2022 at 18:02
To: wolfgangbrandl/db2_fdw ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [wolfgangbrandl/db2_fdw] Having issue while running make. Error: db2ci.h: No such file or directory (Issue #34)

 

Hi @rajkamal321, I'm facing the same issue and I have a couple questions:
where can I find the db2ci.h file
db2 is running on a Linux/Windows machine or on as400?
Thanks

**Comment by RavazziniAndrea** [comment]
Ok thank you..
Do you now something to connect to db2 for as400?

**Comment by wolfgangbrandl** [comment]
Hi
  I think that you can instal db2 luw client or db2 luw Connect.
  Then you could catalog the database in As400. And then you could act as it would be a LUW database.
  DB2 Connect works with MVS database connect.
  As400 i have never tested.
  Regards
  Wolfgang
  
  ----- wolfgangbrandl/db2_fdw wrote -----
  From: Ravazzini Andrea ***@***.***>
  Date: 10.10.2022 14:48
  To: wolfgangbrandl/db2_fdw ***@***.***>
  Cc: Wolfgang Brandl ***@***.***>, Comment ***@***.***>
  Subject: Re: [wolfgangbrandl/db2_fdw] Having issue while running make. Error: db2ci.h: No such file or directory (Issue #34)
  &nbsp; >
