### ISSUE TITLE
fatal error: access/htup_details.h: No such file or directory

### ISSUE THREAD

**Issue by na-tasja** [wolfgangbrandl/db2_fdw#35]
Hiya, 

I've tried installing `db2_fdw` by cloning the repository on an AWS Linux EC2 instance. It clones, but when I run `make` or `sudo make`, I get this error:

```
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -g -fPIC -I/include -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o db2_fdw.o db2_fdw.c
db2_fdw.c:11:10: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [db2_fdw.o] Error 1
```

Any suggestions?

Thank you

**Comment by wolfgangbrandl** [comment]
Hi

Please set the environment Variables PGHOME to where postgres is installed.

And PATH=$PGHOME/bin:$PATH

Then try again.

Which version of postgres is installed?

Regards Wolfgang

 

From: Natasja Laurie ***@***.***>
Reply to: wolfgangbrandl/db2_fdw ***@***.***>
Date: Tuesday, 6. December 2022 at 17:49
To: wolfgangbrandl/db2_fdw ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wolfgangbrandl/db2_fdw] fatal error: access/htup_details.h: No such file or directory (Issue #35)

 

Hiya,

I've tried installing db2_fdw by cloning the repository on an AWS Linux EC2 instance. It clones, but when I run make or sudo make, I get this error:
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -g -fPIC -I/include -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o db2_fdw.o db2_fdw.c
db2_fdw.c:11:10: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [db2_fdw.o] Error 1
Any suggestions?

Thank you

**Comment by wolfgangbrandl** [comment]
Hi

What is installed on the server?

DB2, Postgresql, which version?

 

From: Natasja Laurie ***@***.***>
Reply to: wolfgangbrandl/db2_fdw ***@***.***>
Date: Tuesday, 6. December 2022 at 17:49
To: wolfgangbrandl/db2_fdw ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wolfgangbrandl/db2_fdw] fatal error: access/htup_details.h: No such file or directory (Issue #35)

 

Hiya,

I've tried installing db2_fdw by cloning the repository on an AWS Linux EC2 instance. It clones, but when I run make or sudo make, I get this error:
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -g -fPIC -I/include -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o db2_fdw.o db2_fdw.c
db2_fdw.c:11:10: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [db2_fdw.o] Error 1
Any suggestions?

Thank you
