### ISSUE TITLE
Isolation Level

### ISSUE THREAD

**Issue by snyrkill** [wolfgangbrandl/db2_fdw#47]
I'm on Postgres 15 on Debian 12. Installation went fine and I have been using db2_fdw for while without any problems. Performance is good, this is a great product, thank you Wolfgang!
I ran into my first issue this morning:
I was executing a statement like:

`INSERT INTO psqlschema.mytable SELECT * FROM db2schema.table`

The table on the DB2 side has 230 million rows and has ROW LEVEL locking. 
The problem is that during this transaction the DB2 table was blocked for any inserts. 

The only explanation for the writer block is that the simple select accumulated so many locks that it was escalated to table lock which is not what was expected. By reading the DB2 docs this should only happen in RR isolation level.
I checked and CUR_COMMIT was DISABLED so the Isolation Level should be CS. 
I dont have any DBA access to the DB2 instance so I really can't debug what's going on. 
What might cause this?

Thanks in advance,
-S

**Comment by wolfgangbrandl** [comment]
Hi
Thanks for the applaud.
Before i start investigating the statement can you try the following:
INSERT INTO psqlschema.mytable SELECT * FROM db2schema.table with ur;
or
INSERT INTO psqlschema.mytable SELECT * FROM db2schema.table WITH(NOLOCK)
?
Thanks.

**Comment by snyrkill** [comment]
Hi Wolfgang and thanks.
The 'WITH" clause throws a syntax error in Postgres in both cases.
```
$ echo "select * from db2sta.stod with ur"|psql vedur
ERROR:  syntax error at or near "with"
LINE 1: select * from db2sta.stod with ur
                                  ^
```
The schema was done by "IMPORT FOREIGN SCHEMA"
Now I'm experimenting with creating a foreign table with arbitrary query and include "WITH UR".

Best regards,
-S

**Comment by wolfgangbrandl** [comment]
Hi
You know that hte cases we are trying could result in an inconsistent table?
Would it be an option to transfer the huge db2 table with "export" in db2 and copy in postgresql?
That would bea consistent content.

If not can you also try because you have that environment prepared:
INSERT INTO psqlschema.mytable SELECT * FROM db2schema.table fetch first 10000 rows only
and
INSERT INTO psqlschema.mytable SELECT * FROM db2schema.table fetch next 10000 rows only
works. 

If that works we could iterate with perhaps with a loop

**Comment by wolfgangbrandl** [comment]
\c contrib_regression
DO $$
DECLARE
   cnt INTEGER;
   counter INTEGER := 0 ;
   bulk INTEGER := 2 ;
BEGIN
   SELECT INTO cnt count(*) FROM org;
   WHILE counter <= cnt LOOP
    INSERT INTO orgcopy SELECT * FROM org offset counter rows fetch next bulk rows only;
    counter := counter + bulk ;
    RAISE NOTICE 'Counter: %', counter;
   END LOOP ;
END; $$


try this script. Checge you table name and increase the bulk number to something like 100000

**Comment by snyrkill** [comment]
Hi Wolfgang and thanks for all the suggestions.
As this big table is never updated (inserts only) I can get consistent data with UR if I read up to a certain end-point.
So I will attempt to read all data ending with a certain timestamp, that should do the trick.
This I will attempt to do tomorrow, and the session will be monitored on the DB2 side to check if it locks anything.
Best regards,
-Snorri

**Comment by snyrkill** [comment]
I created the external table with an arbitrary query WITH UR and it ran fine, no locks whatsoever.
Thanks again.
-S
