### ISSUE TITLE
REAL is mapped to TEXT

### ISSUE THREAD

**Issue by snyrkill** [wolfgangbrandl/db2_fdw#48]
When I IMPORT FOREIGN SCHEMA, all REAL columns in DB2 are mapped to TEXT in Postgres.
Is there any special reason for this?

**Comment by wolfgangbrandl** [comment]
Hi
Just for test
Can you insert into db2_fdw.h
SQL_TYPE_REAL
into the enum db2Type and then in db2_fdw.c add
in the function db2ImportForeignSchema
The following
case SQL_TYPE_FLOAT:
      case SQL_TYPE_DECIMAL:
      case SQL_TYPE_DOUBLE:
      **case SQL_TYPE_REAL:**
	if (typeprec < 54)
          if (typeprec == 0)
	    appendStringInfo (&buf, "float(1)");
          else if(typeprec < 0)
	    appendStringInfo (&buf, "float(1)");
	  else
	    appendStringInfo (&buf, "float(%d)", typeprec);
	else
	  appendStringInfo (&buf, "numeric");
	break;

**Comment by wolfgangbrandl** [comment]
Give me a feedback if it converted to float, than i will put into the new version.
Thanks

**Comment by wolfgangbrandl** [comment]
Please check release 6.0.1
