### ISSUE TITLE
Transaction with multiple inserts only commits the last insert

### ISSUE THREAD

**Issue by randycoulman** [wolfgangbrandl/db2_fdw#50]
First, thanks so much for this library! It looks like it could be a great solution for us.

After getting the extension compiled, installed, and connected to a DB2 instance, we started experimenting with some of the kinds of queries we're going to need.

We ran into an issue when doing multiple insert statements to the same table within a transaction (details of inserts simplified):

```sql
begin;
INSERT INTO test (number) VALUES (7);
INSERT INTO test (number) VALUES (8);
INSERT INTO test (number) VALUES (9);
commit;
```

When running this, everything looks like it succeeds, but the table only contains the final entry (with value 9).

We also found that the individual insert statements were taking up to 2 seconds each to complete, where as a simple insert without a transaction completes very quickly.

Is this something that is expected to work and run efficiently? Or have we run into a not-yet-complete part of the implementation?

Thanks again!

**Comment by wolfgangbrandl** [comment]
Hi
The new sources should solve the problem. Will you test it ? Thanks.

**Comment by randycoulman** [comment]
Hi @wolfgangbrandl. Thanks for addressing this! I'll test it out when I can.

**Comment by wolfgangbrandl** [comment]
Hi
I just wanted that you test it before i put it onto PGXN.
I have uploaded wit h
db2_fdw 6.0.1

**Comment by randycoulman** [comment]
@wolfgangbrandl Sorry for the delay in getting back to you. I was able to re-test with v6.0.1 this morning, and it resolves both problems I reported above: the insert speed is much more in line with my expectations, and all of the records were inserted as expected.

I'll close this issue since it's been resolved to my satisfaction.

Thank you!
